[book]
title = "cutler - Cookbook"
author = "Anindya Shiddhartha"
description = "Documentation for cutler - a fast, declarative settings manager for the Mac"
language = "en"
src = "src"

[output.html]
default-theme = "machlit"
preferred-dark-theme = "machlit"
additional-css = ["./theme/machlit.css"]

[output.html.search]
limit-results = 15
