name: Release Builds

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-unix:
    runs-on: macos-14
    env:
      FILE_NAME: target/release/cutler-${{ github.event.release.name }}-darwin-arm64.zip

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: cargo build --release --verbose --locked

      - name: Compress binary
        run: zip -j ${{ env.FILE_NAME }} target/release/cutler

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.FILE_NAME }}
          retention-days: 90

      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.FILE_NAME }}
          tag: ${{ github.ref }}
          overwrite: true

  publish:
    needs: [build-unix]
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate markdown for cargo
        run: |
          chmod +x generate_md.sh
          ./generate_md.sh

      - name: Publish using cargo
        run: cargo publish --token ${{ secrets.CRATES_TOKEN }} --allow-dirty
